function(print_arguments_for_cmake_parse_arguments prefix)
    foreach(ITEM ${ARGN} UNPARSED_ARGUMENTS KEYWORDS_MISSING_VALUES)
        message("${prefix}_${ITEM}=${${prefix}_${ITEM}}")
    endforeach()
endfunction()
macro(parse_arguments ARGV0 ARGV1 ARGV2 ARGV3)
    string(STRIP "${ARGV0}" _parse_argv)
    if("${_parse_argv}" STREQUAL "PARSE_ARGV")
        set(_n "${ARGV1}")
        set(_prefix "${ARGV2}")
        set(_options "${ARGV3}")
        set(_one_value_keywords "${ARGV4}")
        set(_multi_value_keywords "${ARGV5}")
        list(GET ARGC 0 _argc)
        set(_parse_argv TRUE)
    else()
        set(_n 0)
        set(_prefix "${_parse_argv}")
        set(_options "${ARGV1}")
        set(_one_value_keywords "${ARGV2}")
        set(_multi_value_keywords "${ARGV3}")
        set(_argn ${ARGN})
        list(LENGTH _argn _argc)
        set(_parse_argv FALSE)
    endif()
    math(EXPR _argc "${_argc}-1")
    foreach(_item IN LISTS _options _one_value_keywords _multi_value_keywords)
        if(_item IN_LIST _checked_list)
            list(APPEND _duplicates ${_item})
        else()
            list(APPEND _checked_list ${_item})
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _duplicates)
    if(_duplicates)
        message(FATAL_ERROR "keyword defined more than once: ${_duplicates}")
    endif()
    foreach(_item IN LISTS _options)
        set(${_prefix}_${_item} FALSE)
    endforeach()
    foreach(_index RANGE ${_n} ${_argc})
        if(_parse_argv)
            set(_item ${ARGV${_index}})
        else()
            list(GET _argn ${_index} _item)
        endif()
        if(_item IN_LIST _options)
            set(${_prefix}_${_item} TRUE)
            unset(_current_key)
        elseif(_item IN_LIST _one_value_keywords)
            set(_current_key ${_item})
            set(${_prefix}_${_current_key}_HAS TRUE)
        elseif(_item IN_LIST _multi_value_keywords)
            set(_current_key ${_item})
            set(${_prefix}_${_current_key}_HAS TRUE)
            list(LENGTH ${_prefix}_${_current_key} _length)
            list(APPEND ${_prefix}_${_current_key} ${_length})
        else()
            if(_current_key IN_LIST _one_value_keywords)
                set(${_prefix}_${_current_key} "${_item}")
                unset(_current_key)
            elseif(_current_key IN_LIST _multi_value_keywords)
                list(APPEND ${_prefix}_${_current_key}_${_length} ${_item})
            else()
                list(APPEND ${_prefix}_UNPARSED_ARGUMENTS ${_item})
            endif()
        endif()
    endforeach()
    foreach(_item IN LISTS _one_value_keywords)
        if(NOT DEFINED ${_prefix}_${_item} AND ${_prefix}_${_item}_HAS)
            list(APPEND ${_prefix}_KEYWORDS_MISSING_VALUES ${_item})
            unset(${_prefix}_${_item}_HAS)
        endif()
    endforeach()
    foreach(_item IN LISTS _multi_value_keywords)
        unset(_checked_list)
        foreach(_index IN LISTS ${_prefix}_${_item})
            list(LENGTH ${_prefix}_${_item}_${_index} _length)
            if(NOT _length)
                list(APPEND _checked_list ${_index})
            endif()
        endforeach()
        list(REMOVE_ITEM ${_prefix}_${_item} ${_checked_list})
        list(LENGTH "${_prefix}_${_item}" _length)
        if(NOT _length AND ${_prefix}_${_item}_HAS)
            unset(${_prefix}_${_item})
            unset(${_prefix}_${_item}_HAS)
            list(APPEND ${_prefix}_KEYWORDS_MISSING_VALUES ${_item})
        endif()
    endforeach()
    list(REMOVE_DUPLICATES ${_prefix}_KEYWORDS_MISSING_VALUES)
endmacro()