# 查找相应目录下所有包含CMakeLists.txt文件的子目录,并按要求add_subdirectory
function(add_directories)
    set(options)
    set(one_value_keywords)
    set(multi_value_keywords INCLUDE EXCLUDE)

    set(PREFIX ${CMAKE_CURRENT_FUNCTION})
    cmake_parse_arguments(PARSE_ARGV 0 ${PREFIX} "${options}" "${one_value_keywords}" "${multi_value_keywords}")

    if (DEFINED ${PREFIX}_INCLUDE)
        foreach(ITEM IN LISTS ${PREFIX}_INCLUDE)
            cmake_path(ABSOLUTE_PATH ITEM)
            cmake_path(APPEND CMAKE_FILE ${ITEM} CMakeLists.txt)
            if(EXISTS ${CMAKE_FILE})
                list(APPEND ${PREFIX}_INCLUDE ${ITEM})
            endif()
        endforeach()
    else()
        file(GLOB WALK *)
        foreach(ITEM IN LISTS WALK)
            cmake_path(APPEND CMAKE_FILE ${ITEM} CMakeLists.txt)
            if(EXISTS ${CMAKE_FILE})
                list(APPEND ${PREFIX}_INCLUDE ${ITEM})
            endif()
        endforeach()
    endif()
    foreach(ITEM IN LISTS ${PREFIX}_EXCLUDE)
        cmake_path(ABSOLUTE_PATH ITEM)
        list(REMOVE_ITEM ${PREFIX}_INCLUDE ${ITEM})
    endforeach()
    foreach(ITEM IN LISTS ${PREFIX}_INCLUDE)
        add_subdirectory(${ITEM})
    endforeach()
endfunction()

function(router_files)
    cmake_parse_arguments(${CMAKE_CURRENT_FUNCTION} "" "INCLUDES;EXCLUDES" "" ${ARGN})
    file(GLOB WALK LIST_DIRECTORIES FALSE RELATIVE ${CMAKE_CURRENT_LIST_DIR} "${${CMAKE_CURRENT_FUNCTION}_INCLUDES}")

    
    if(${CMAKE_CURRENT_FUNCTION}_EXCLUDES)
        list(REMOVE_ITEM WALK "${${CMAKE_CURRENT_FUNCTION}_EXCLUDES}")
    endif()
    
    foreach(ITEM IN LISTS WALK)
        cmake_path(GET ITEM STEM LAST_ONLY PROJ)
        add_executable(${PROJ} ${ITEM})
    endforeach()
endfunction()