function(add_subdirectories)
    set(options)
    set(one_value_keywords)
    set(multi_value_keywords INCLUDE EXCLUDE)
    set(PREFIX ${CMAKE_CURRENT_FUNCTION})
    cmake_parse_arguments(${PREFIX} "${options}" "${one_value_keywords}" "${multi_value_keywords}" ${ARGN})
    file(REAL_PATH ~ USER_HOME EXPAND_TILDE)
    list(TRANSFORM ${PREFIX}_EXCLUDE STRIP)
    list(TRANSFORM ${PREFIX}_EXCLUDE REPLACE ^~ "${USER_HOME}")
    foreach(ITEM IN LISTS ${PREFIX}_EXCLUDE)
        cmake_path(ABSOLUTE_PATH ITEM NORMALIZE)
        if(IS_DIRECTORY "${ITEM}")
            file(REAL_PATH "${ITEM}" ITEM)
            list(APPEND _${PREFIX}_EXCLUDE "${ITEM}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _${PREFIX}_EXCLUDE)
    if (DEFINED ${PREFIX}_INCLUDE)
        list(TRANSFORM ${PREFIX}_INCLUDE STRIP)
        list(TRANSFORM ${PREFIX}_INCLUDE REPLACE ^~ "${USER_HOME}")
    else()
        file(GLOB ${PREFIX}_INCLUDE *)
    endif()
    foreach(ITEM IN LISTS ${PREFIX}_INCLUDE)
        cmake_path(ABSOLUTE_PATH ITEM NORMALIZE)
        if(IS_DIRECTORY "${ITEM}")
            file(REAL_PATH "${ITEM}" ITEM)
            cmake_path(APPEND CMAKE_FILE "${ITEM}" CMakeLists.txt)
            if((EXISTS "${CMAKE_FILE}") AND NOT (ITEM IN_LIST _${PREFIX}_EXCLUDE))
                list(APPEND _${PREFIX}_EXCLUDE "${ITEM}")
                add_subdirectory("${ITEM}")
            endif()
        endif()
    endforeach()
endfunction()